### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by eacunaf** [hammerlab/knnimpute#1]
Dear Sir,
When I am running knn impute I am getting this error message

[KNN] Warning: 104/77964 still missing after imputation, replacing with 0

Could you please tell me its meaning?

Bst,
Edgar Acuna
University of Puerto Rico

**Comment by iskandr** [comment]
Some of the samples did not have enough overlapping (non-missing) entries to find their neighbors, so their missing values are being zero-filled.

**Comment by eacunaf** [comment]
Thank you. I realized already this was the problem. Because I ran my R
program to do that and I got a message similar to the one
taht you mention me.

Best,
Edgar

2017-03-15 16:10 GMT-04:00 Alex Rubinsteyn <notifications@github.com>:
