### ISSUE TITLE
Distance zero leads to division by zero and NaN

### ISSUE THREAD

**Issue by amueller** [hammerlab/knnimpute#3]
This seems to be failing on a toy example.
I haven't checked the code yet but here's how to reproduce:

```python
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()
X, y = iris.data, iris.target
# some values missing only
rng = np.random.RandomState(0)
X_some_missing = X.copy()
mask = np.abs(X[:, 2] - rng.normal(loc=5.5, scale=.7, size=X.shape[0])) < .6
X_some_missing[mask, 3] = np.NaN
# different random numbers
mask2 = np.abs(X[:, 2] - rng.normal(loc=5.5, scale=.7, size=X.shape[0])) < .6
X_some_missing[mask2, 2] = np.NaN

from fancyimpute import KNN
res = KNN().complete(X_some_missing)
```
> [KNN] Warning: 6/600 still missing after imputation, replacing with 0

**Comment by amueller** [comment]
Same with
```python
res = knnimpute.knn_impute_few_observed(X_some_missing, np.isnan(X_some_missing), k=3)
np.isnan(res).any()
```
> True

```python
res = knnimpute.knn_impute_with_argpartition(X_some_missing, np.isnan(X_some_missing), k=3)
np.isnan(res).any()
```
> True

While 
```python
res = knnimpute.knn_impute_optimistic(X_some_missing, np.isnan(X_some_missing), k=3)
```
crashes....

**Comment by amueller** [comment]
There's a division by zero error if the distance is zero:
```python
X = np.array([[1, 1, np.NaN], [1, 1, 1]])
knnimpute.knn_impute_few_observed(X, np.isnan(X), k=1)
```
>array([[  1.,   1.,  nan],
       [  1.,   1.,   1.]])

That seems to happen in all methods. Maybe changing the distance computation to not return 0 but a small epsilon would be easiest?
It's not clear to me how much we might want to smooth if the distance is zero. We could set epsilon to 1e-10 which basically would be a hard assignment?

**Comment by amueller** [comment]
Any ideas on what the best fix is @iskandr @sergeyf? I'd like to use this in class but currently it doesn't work with duplicate or near duplicate points.

**Comment by sergeyf** [comment]
@amueller I'll take a look.

**Comment by sergeyf** [comment]
@iskandr @amueller Here is a fix for `knn_impute_few_observed`.
```
    max_distance = np.maximum(D[finite_distance_distance_mask].max(), 1e-6)
    effective_infinity = 10 ** 6 * max_distance
    D[~finite_distance_distance_mask] = effective_infinity
    D_sorted = np.argsort(D, axis=1)
    inv_D = 1.0 / np.maximum(D, 1e-6)
```
There are two changes here: (i) we want to make sure that `effective_infinity` can't be 0 and we want to make sure that `inv_D` has no infinities. 

I'm still looking at the other versions.

**Comment by sergeyf** [comment]
Actually, here is a fix that makes all of @amueller's examples work:

```
def knn_initialize(X, missing_mask, verbose=False, min_dist=1e-6):
    """
    Fill X with NaN values if necessary, construct the n_samples x n_samples
    distance matrix and set the self-distance of each row to infinity.
    """
    X_row_major = X.copy("C")
    if missing_mask.sum() != np.isnan(X_row_major).sum():
        # if the missing values have already been zero-filled need
        # to put NaN's back in the data matrix for the distances function
        X_row_major[missing_mask] = np.nan
    D = all_pairs_normalized_distances(X_row_major, verbose=verbose)
    # set diagonal of distance matrix to infinity since we don't want
    # points considering themselves as neighbors
    max_dist = 1e6 * np.maximum(1, D.max())
    for i in range(X.shape[0]):
        D[i, i] = max_dist
    D[D < min_dist] = min_dist
    D[D > max_dist] = max_dist
    return X_row_major, D
```

I'll open a pull request.

**Comment by amueller** [comment]
I was also thinking whether you might already want to do something in ``all_pairs_normalized_distances`` but maybe that's too hacky.

Your's looks decent. Thanks!

**Comment by iskandr** [comment]
The only thing we lose by always having non-zero finite distances is that we'll impute in all cases (we'll have to drop the `if weights.sum() > 0` logic) but I don't see why that's any worse than leaving some entries as NaN.

**Comment by iskandr** [comment]
@amueller I'll add your iris example as a unit test once Sergey's PR is merged.

**Comment by sergeyf** [comment]
I think it's actually better. The only time I would expect to have no imputation at all is something like this:

```
array([[ nan,   1.],
       [  1.,  nan]])
```

And it does work:

```
knn_impute_few_observed(X, np.isnan(X), 1)
Out[62]: 
array([[ nan,   1.],
       [  1.,  nan]])
```

**Comment by amueller** [comment]
Thanks :)

**Comment by sergeyf** [comment]
Hope it goes well with the teaching!
